### PR TITLE
Jovin leong

### PR DESCRIPTION
**Pull request by JovinLeong**
Hi, I'm trying to pull

### CODE REVIEW

**Comment by lindseysbrown** [comment]
Missing screenshot of merge conflict.

Problem 3: 46/50

**Comment by JovinLeong** [comment]
The screenshot is there; it's definitely not in my playground repo since we were told to have it in our HW1-final repo :/

**Comment by lindseysbrown** [comment]
Jovin, please submit a formal regrade request per the instructions on Piazza if you have not already done so.

You are correct that the screenshots can be in your HW1-final repo.  You did not send me an invite to your course repo, so I cannot grade a private repository that I don't have access to.

**Comment by JovinLeong** [comment]
Yup, I've sent an email a couple of days back - thanks again!

I could only add three of the 5 listed instructors because I wasn't on Github Pro, but Michael Buch informed me that I should get Pro so I'll be sending out the invite shortly. Cheers!

**Pull request closed without merging**
